Invariant_Classification:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.SingleTowerMAEDataset
    data_dir: "data/newdata_big/Invariant_Classification"
    encoder_domain: "digit"
    decoder_domain: "mae_recon_single"
    random_resize_crop: ${datasets.VAR_random_resize_crop}
    random_hv_flip_prob: ${datasets.VAR_random_hv_flip_prob}
    color_jitter: ${datasets.VAR_color_jitter}
    img_norm:
      mean: [0.24818, 0.34187, 0.33843]
      std: [0.17062, 0.11911, 0.16373]

Invariant_Pose:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.SingleTowerMAEDataset
    data_dir: "data/newdata_big/Invariant_Pose"
    encoder_domain: "digit"
    decoder_domain: "mae_recon_single"
    random_resize_crop: ${datasets.VAR_random_resize_crop}
    random_hv_flip_prob: ${datasets.VAR_random_hv_flip_prob}
    color_jitter: ${datasets.VAR_color_jitter}
    img_norm:
      mean: [0.32900, 0.42795, 0.43899]
      std: [0.20861, 0.10615, 0.14590]

NeuralFeels:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.SingleTowerMAEDataset
    data_dir: "data/newdata_big/NeuralFeels"
    encoder_domain: "digit"
    decoder_domain: "mae_recon_single"
    random_resize_crop: ${datasets.VAR_random_resize_crop}
    random_hv_flip_prob: ${datasets.VAR_random_hv_flip_prob}
    color_jitter: ${datasets.VAR_color_jitter}
    img_norm:
      mean: [0.39444, 0.39553, 0.37566]
      std: [0.14445, 0.08409, 0.10544]